export const MEMORY_SIZE = 128;

export const INPUT_SIZE = 16;
export const OUTPUT_SIZE = 16;

const INPUT_START = MEMORY_SIZE - INPUT_SIZE - OUTPUT_SIZE;
const OUTPUT_START = MEMORY_SIZE - OUTPUT_SIZE;

export const INPUT_RANGE = [INPUT_START, OUTPUT_START];
export const OUTPUT_RANGE = [OUTPUT_START, MEMORY_SIZE];
